// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import generator "github.com/Szymongib/go-collagen/internal/generator"
import mock "github.com/stretchr/testify/mock"

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// FindStruct provides a mock function with given fields: structName, path
func (_m *Parser) FindStruct(structName string, path string) (generator.Struct, error) {
	ret := _m.Called(structName, path)

	var r0 generator.Struct
	if rf, ok := ret.Get(0).(func(string, string) generator.Struct); ok {
		r0 = rf(structName, path)
	} else {
		r0 = ret.Get(0).(generator.Struct)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(structName, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
